#' Trimer Frequency Comparison
#'
#' This function computes trimer frequency comparison for given Nmer frequency table.
#'
#' @param Nmerfrequencytable A data.table generated by Nmerfrequency with Nmer=3
#' @return A data.table with summed trimer frequencies for complements
#'
#' @examples
#' # Assuming `Nmerfrequencytable` is already defined
#' trimerfrequencycomp(Nmerfrequencytable)
#'
#' @export
trimerfrequencycomp <- function(Nmerfrequencytable) {
  # Check if Nmerfrequencytable is a data.table
  if (!is.data.table(Nmerfrequencytable)) {
    stop("Nmerfrequencytable must be a data.table")
  }

  all_trimers <- do.call(paste0, expand.grid(rep(list(c("A", "T", "C", "G")), 3)))

  comptrimers <- c("ACA","ACC","ACG","ACT","ACA","ACC","ACG","ACT","ACA","ACC","ACG","ACT",
                   "ATA","ATC","ATG","ATT","ATA","ATC","ATG","ATT","ATA","ATC","ATG","ATT",
                   "CCA","CCC","CCG","CCT","CCA","CCC","CCG","CCT","CCA","CCC","CCG","CCT",
                   "CTA","CTC","CTG","CTT","CTA","CTC","CTG","CTT","CTA","CTC","CTG","CTT",
                   "GCA","GCC","GCG","GCT","GCA","GCC","GCG","GCT","GCA","GCC","GCG","GCT",
                   "GTA","GTC","GTG","GTT","GTA","GTC","GTG","GTT","GTA","GTC","GTG","GTT",
                   "TCA","TCC","TCG","TCT","TCA","TCC","TCG","TCT","TCA","TCC","TCG","TCT",
                   "TTA","TTC","TTG","TTT","TTA","TTC","TTG","TTT","TTA","TTC","TTG","TTT")

  newtable <- data.table(ID = Nmerfrequencytable$ID)

  # Function to get reverse complement
  rev_comp <- function(x) {
    rev <- rev(unlist(strsplit(x, split = "")))
    paste0(toupper(comp(rev)), collapse = "")
  }

  cols <- colnames(Nmerfrequencytable)[colnames(Nmerfrequencytable) %in% all_trimers]

  for (COL in cols) {
    if (COL %in% comptrimers) {
      revcomp <- rev_comp(COL)
      if (revcomp %in% colnames(Nmerfrequencytable)) {
        newtable[, (COL) := rowSums(Nmerfrequencytable[, .(get(COL), get(revcomp))], na.rm = TRUE)]
      }
    }
  }


  return(newtable)
}
