#' Trimer Frequency Comparison
#'
#' This function computes trimer frequency comparison for given Nmer frequency table.
#'
#' @param Nmerfrequencytable A data.table generated by Nmerfrequency with Nmer=3
#' @return A data.table with summed trimer frequencies for complements
#'
#' @examples
#' # Assuming `Nmerfrequencytable` is already defined
#' trimerfrequencycomp(Nmerfrequencytable)
#'
#' @export
trimerfrequencycomp <- function(Nmerfrequencytable) {
  # Check if Nmerfrequencytable is a data.table
  if (!is.data.table(Nmerfrequencytable)) {
    stop("Nmerfrequencytable must be a data.table")
  }

  all_trimers <- do.call(paste0, expand.grid(rep(list(c("A", "T", "C", "G")), 3)))

  # Trimers with pyrimidine (C or T) at the middle position — the 32 contexts
  # used for complement-merging in the SBS mutation signature convention
  comptrimers <- do.call(paste0, expand.grid(
    c("A","T","C","G"),
    c("C","T"),
    c("A","T","C","G")
  ))

  newtable <- data.table(ID = Nmerfrequencytable$ID)

  # Function to get reverse complement
  rev_comp <- function(x) {
    rev <- rev(unlist(strsplit(x, split = "")))
    paste0(toupper(comp(rev)), collapse = "")
  }

  cols <- colnames(Nmerfrequencytable)[colnames(Nmerfrequencytable) %in% all_trimers]

  for (COL in cols) {
    if (COL %in% comptrimers) {
      revcomp <- rev_comp(COL)
      if (revcomp %in% colnames(Nmerfrequencytable)) {
        newtable[, (COL) := rowSums(Nmerfrequencytable[, .(get(COL), get(revcomp))], na.rm = TRUE)]
      }
    }
  }


  return(newtable)
}
